# Generated by Django 5.2.8 on 2025-12-23 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите категорию товара",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="catalog",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
    ]
