# Generated by Django 5.2.8 on 2026-01-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Счетчик просмотров продукта",
                verbose_name="Количество просмотров",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото товара",
                null=True,
                upload_to="product/photo",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Введите цену за покупку",
                max_digits=10,
                verbose_name="Цена за покупку",
            ),
        ),
    ]
